import { randomBytes } from 'node:crypto';
import { mkdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';
import { createApp } from './app.mjs';
import { ollamaProvider } from './provider.mjs';

const dataDir=fileURLToPath(new URL('../data/',import.meta.url));
mkdirSync(dataDir,{recursive:true,mode:0o700});
const tokenFile=`${dataDir}/pairing-token`;
if(!existsSync(tokenFile)) writeFileSync(tokenFile,randomBytes(32).toString('hex'),{mode:0o600});
const token=process.env.SIGHTLINE_TOKEN||readFileSync(tokenFile,'utf8').trim();
const port=Number(process.env.PORT||9041);
const host=process.env.HOST||'127.0.0.1';
if(host!=='127.0.0.1' && (!process.env.SIGHTLINE_TOKEN||!process.env.PUBLIC_ORIGIN?.startsWith('https://'))) throw new Error('Public hosting requires SIGHTLINE_TOKEN and an HTTPS PUBLIC_ORIGIN');
const db=new DatabaseSync(`${dataDir}/audit.sqlite`);
db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY, createdAt TEXT NOT NULL, model TEXT NOT NULL, mode TEXT NOT NULL, controls INTEGER NOT NULL, regions INTEGER NOT NULL, latencyMs REAL NOT NULL, actionType TEXT NOT NULL)');
const insert=db.prepare('INSERT INTO audit VALUES (?,?,?,?,?,?,?,?)');
const app=createApp({token,publicOrigin:process.env.PUBLIC_ORIGIN||`http://127.0.0.1:${port}`,origins:(process.env.ALLOWED_ORIGINS||'').split(',').filter(Boolean),infer:ollamaProvider({baseUrl:process.env.OLLAMA_URL||'http://127.0.0.1:11434',model:process.env.OLLAMA_MODEL||'qwen2.5:7b-instruct'}),saveAudit:r=>{insert.run(r.id,r.createdAt,r.model,r.mode,r.controls,r.regions,r.latencyMs,r.actionType);db.exec('DELETE FROM audit WHERE id NOT IN (SELECT id FROM audit ORDER BY createdAt DESC LIMIT 1000)');},readAudits:()=>db.prepare('SELECT * FROM audit ORDER BY createdAt DESC LIMIT 100').all()});
app.listen(port,host,()=>console.log(`Sightline prototype: http://${host}:${port}. Pairing token remains in local data storage.`));
for(const signal of ['SIGINT','SIGTERM']) process.on(signal,()=>app.close(()=>{db.close();process.exit(0);}));
