import test from 'node:test';import assert from 'node:assert/strict';import {runTask} from '../shared/task-loop.mjs';
const click={action:{type:'click',targetId:'c0'}};
function fixture(){let state=0;return {observe:async()=>({complete:state===2,fingerprint:'state'+state}),plan:async()=>click,execute:async()=>{state++;}};}
test('two-step run reports completion only after observing the postcondition',async()=>{const r=await runTask(fixture());assert.equal(r.status,'completed');assert.equal(r.actions,2);assert.equal(r.trace.filter(x=>x.state==='observe').length,3);});
test('premature done is not task success',async()=>{const r=await runTask({...fixture(),plan:async()=>({action:{type:'done'}})});assert.equal(r.reason,'completion_unverified');assert.equal(r.actions,0);});
test('unchanged page stops without an unbounded retry loop',async()=>{const r=await runTask({...fixture(),execute:async()=>{}});assert.equal(r.reason,'no_progress');assert.equal(r.actions,2);});
test('step budget still permits final postcondition verification',async()=>{const r=await runTask({...fixture(),maxSteps:2});assert.equal(r.status,'completed');const s=await runTask({...fixture(),maxSteps:1});assert.equal(s.reason,'step_limit');});
test('cancelled planner cannot execute a late result',async()=>{const controller=new AbortController();let executions=0,release,entered;const ready=new Promise(r=>entered=r);const running=runTask({...fixture(),signal:controller.signal,plan:()=>{entered();return new Promise(r=>release=r);},execute:async()=>executions++});await ready;controller.abort();const r=await running;release(click);await new Promise(r=>setImmediate(r));assert.equal(r.status,'cancelled');assert.equal(executions,0);});
test('deadline releases a stalled observation and never executes',async()=>{let executed=false;const r=await runTask({...fixture(),deadlineMs:10,observe:()=>new Promise(()=>{}),execute:async()=>executed=true});assert.equal(r.reason,'deadline');assert.equal(executed,false);});
test('execution error requires review and is never retried',async()=>{let calls=0;const r=await runTask({...fixture(),execute:async()=>{calls++;throw new Error('private-token-secret');}});assert.equal(r.reason,'execution_requires_review');assert.equal(calls,1);assert.equal(JSON.stringify(r).includes('private-token-secret'),false);});
test('malformed planner result and observation fail without execution',async()=>{let calls=0;for(const overrides of [{plan:async()=>({action:{type:'script'}})},{observe:async()=>({complete:'yes',fingerprint:'x'})}]){const r=await runTask({...fixture(),...overrides,execute:async()=>calls++});assert.equal(r.status,'stopped');}assert.equal(calls,0);});
test('abort before start performs no capture',async()=>{const c=new AbortController();c.abort();let calls=0;const r=await runTask({...fixture(),signal:c.signal,observe:async()=>{calls++;}});assert.equal(r.status,'cancelled');assert.equal(calls,0);});
test('invalid budgets are rejected before adapters run',async()=>{for(const extra of [{maxSteps:0},{deadlineMs:0},{maxNoProgress:0}])await assert.rejects(runTask({...fixture(),...extra}),/budget/);});
