'use strict';
const stages={fast:{location:'FAST PATH · ON DEVICE',title:'Capture → detect → mask → privacy review.',description:'Toolbar capture, UltraFace WASM, selective or wireframe preview, sanitize, human review. No planner network call. Extension popup shows local capture timing with an explicit “not G11 full-flow” label.',limit:'SLO: local protect diagnostic only. Fast ≠ G11. G11 remains fail until Reason-inclusive p95 <200 ms at n≥100.'},score:{location:'SCORE PATH · LOCAL HEURISTIC',title:'Local risk band after Fast protect.',description:'After Capture & protect, Score ranks local scene risk from opaque region kinds and allowlisted controls. Runnable in the extension popup. officialScore stays null — organizer accuracy+PII+redaction weights ≈65% are evaluation weights, not our measured score. Not WebPII.',limit:'SLO: diagnostic risk band only. Not a G11 pass. Do not treat this band as the official SIH weighted total.'},reason:{location:'REASON PATH · LOCAL MODEL',title:'Ollama/Qwen plan + human confirm.',description:'Authenticated Node API sends semantics-only layout to local Qwen2.5 via Ollama; bounded click/scroll/done requires explicit confirm. Pixels stay on device.',limit:'SLO: outside <200 ms today (historical responses seconds). Included in G11 full-flow; gate stays fail until p95 <200 ms at n≥100. DigiLocker-inspired chrome is a trust pattern only — not partner, API, or custody.'}};
document.querySelectorAll('[data-stage]').forEach(button=>button.addEventListener('click',()=>{const selected=stages[button.dataset.stage];if(!selected)return;document.querySelectorAll('[data-stage]').forEach(node=>{node.classList.toggle('selected',node===button);node.setAttribute('aria-pressed',String(node===button));});document.getElementById('stage-location').textContent=selected.location;document.getElementById('stage-title').textContent=selected.title;document.getElementById('stage-description').textContent=selected.description;document.getElementById('stage-limit').textContent=selected.limit;}));
const dialog=document.getElementById('demo-dialog');let opener=null;
document.querySelectorAll('[data-open-demo]').forEach(button=>button.addEventListener('click',()=>{opener=button;dialog.showModal();document.getElementById('close-dialog').focus();}));
document.getElementById('close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(opener)opener.focus();});dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();}});
document.getElementById('copy-setup').addEventListener('click',async()=>{const status=document.getElementById('copy-status');try{await navigator.clipboard.writeText(document.getElementById('setup-command').textContent);status.textContent='Setup commands copied.';}catch{status.textContent='Copy was unavailable. Select the commands above to copy them manually.';}});
document.getElementById('share').addEventListener('click',async()=>{const status=document.getElementById('share-status');if(['localhost','127.0.0.1','[::1]'].includes(location.hostname)||location.protocol==='file:'){status.textContent='This is a local preview. Share the source repository until the public page is verified.';return;}try{await navigator.clipboard.writeText(location.href.split('#')[0]);status.textContent='Page link copied.';}catch{status.textContent='Copy was unavailable. Use the address bar to copy this page link.';}});
if('IntersectionObserver' in window&&matchMedia('(prefers-reduced-motion: no-preference)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}});},{threshold:.07});document.querySelectorAll('.section-heading,.boundary-card,.team-list,.timeline').forEach(element=>{element.classList.add('reveal-ready');observer.observe(element);});}

(()=>{const en=document.getElementById('site-lang-en');const hi=document.getElementById('site-lang-hi');if(!en||!hi)return;const copy={en:{trust:'on this device',trustTitle:'Capture and privacy filter run on-device. What can leave: semantic scene fields only. Raw pixels stay local. DigiLocker-inspired trust pattern only — not a partner, API, or custody claim.',demo:'Run local demo'},hi:{trust:'इस उपकरण पर',trustTitle:'कैप्चर और गोपनीयता फ़िल्टर इस उपकरण पर चलते हैं। बाहर जा सकता है: केवल अर्थ-दृश्य फ़ील्ड। कच्चे पिक्सेल स्थानीय रहते हैं। DigiLocker-प्रेरित विश्वास पैटर्न मात्र — भागीदार/API/कस्टडी दावा नहीं।',demo:'स्थानीय डेमो चलाएँ'}};function apply(lang){document.documentElement.lang=lang==='hi'?'hi':'en';en.setAttribute('aria-pressed',String(lang==='en'));hi.setAttribute('aria-pressed',String(lang==='hi'));const t=copy[lang];const te=document.getElementById('trust-en');const th=document.getElementById('trust-hi');const bar=document.getElementById('trust-bar');if(te)te.textContent=lang==='en'?t.trust:'on this device';if(th){th.textContent=copy.hi.trust;th.hidden=lang==='en';}if(te)te.hidden=lang==='hi';if(bar)bar.title=t.trustTitle;document.querySelectorAll('[data-i18n-demo]').forEach(btn=>{const icon=btn.querySelector('[aria-hidden]');btn.childNodes[0].textContent=t.demo+' ';});}en.addEventListener('click',()=>apply('en'));hi.addEventListener('click',()=>apply('hi'));})();
