'use strict';
const stages={capture:{location:'INSIDE THE BROWSER',title:'A capture you initiate.',description:'The web demonstration captures its synthetic fixture with html2canvas. The extension package uses native active-tab capture. Original pixels remain in client memory.',limit:'Native Chrome and Firefox extension execution still needs browser-specific validation.'},protect:{location:'ON YOUR DEVICE',title:'A deliberately smaller scene.',description:'UltraFace runs locally through ONNX Runtime Web and WASM. DOM bounds and privacy rules turn the page into opaque regions, geometry and approved control labels. Original image pixels and free text are excluded from the request.',limit:'Face detection can miss small or occluded faces. The output never authorizes raw image transmission. Dataset accuracy and retained visual utility still need measurement.'},reason:{location:'THE LOCAL MODEL SERVER',title:'Reasoning from approved context.',description:'An authenticated Node.js API passes the protected semantic layout to Qwen2.5:7b-instruct through Ollama. The server returns a bounded click, scroll or done proposal.',limit:'This build uses a text LLM interpreting layout geometry and labels. It does not claim pixel-reading VLM inference, and model responses currently take seconds.'},act:{location:'BACK IN THE BROWSER',title:'Review first. Then execute.',description:'You inspect and confirm the proposed action. The browser checks the approved target and current scene revision before execution. Changed or expired captures require a new review.',limit:'The current synthetic workflow uses an approved control vocabulary. Arbitrary navigation, typing and irreversible submissions are not implemented.'}};
document.querySelectorAll('[data-stage]').forEach(button=>button.addEventListener('click',()=>{const selected=stages[button.dataset.stage];if(!selected)return;document.querySelectorAll('[data-stage]').forEach(node=>{node.classList.toggle('selected',node===button);node.setAttribute('aria-pressed',String(node===button));});document.getElementById('stage-location').textContent=selected.location;document.getElementById('stage-title').textContent=selected.title;document.getElementById('stage-description').textContent=selected.description;document.getElementById('stage-limit').textContent=selected.limit;}));
const dialog=document.getElementById('demo-dialog');let opener=null;
document.querySelectorAll('[data-open-demo]').forEach(button=>button.addEventListener('click',()=>{opener=button;dialog.showModal();document.getElementById('close-dialog').focus();}));
document.getElementById('close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(opener)opener.focus();});dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();}});
document.getElementById('copy-setup').addEventListener('click',async()=>{const status=document.getElementById('copy-status');try{await navigator.clipboard.writeText(document.getElementById('setup-command').textContent);status.textContent='Setup commands copied.';}catch{status.textContent='Copy was unavailable. Select the commands above to copy them manually.';}});
document.getElementById('share').addEventListener('click',async()=>{const status=document.getElementById('share-status');if(['localhost','127.0.0.1','[::1]'].includes(location.hostname)||location.protocol==='file:'){status.textContent='This is a local preview. Share the source repository until the public page is verified.';return;}try{await navigator.clipboard.writeText(location.href.split('#')[0]);status.textContent='Page link copied.';}catch{status.textContent='Copy was unavailable. Use the address bar to copy this page link.';}});
if('IntersectionObserver' in window&&matchMedia('(prefers-reduced-motion: no-preference)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}});},{threshold:.07});document.querySelectorAll('.section-heading,.boundary-card,.team-list,.timeline').forEach(element=>{element.classList.add('reveal-ready');observer.observe(element);});}
